services:
  - type: web
    name: cron-humanize
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile
    startCommand: bundle exec thrust bundle exec puma -C config/puma.rb
    healthCheckPath: /up
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: GOOGLE_ANALYTICS_ID
        sync: false
